logging.level.org.springframework.context.annotation.ClassPathBeanDefinitionScanner=DEBUG
logging.level.org.springframework.beans.factory=INFO

server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.directory=/Users/vijaygarothaya/work/product/neasaa-finance/logs
server.tomcat.accesslog.prefix=access_log
server.tomcat.accesslog.suffix=.log
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b %D
#server.tomcat.accesslog.pattern=common
#server.tomcat.accesslog.pattern=combined
server.tomcat.accesslog.rotate=true
server.tomcat.basedir=.

# Enable CORS in development, disable in production
cors.enabled=true

email.sender.emailid=neasaa.finance@gmail.com
email.sender.displayname=Neasaa Finance
#email.sender.replyto.emailid=rajputchhipasamaj@gmail.com

email.server.host=smtp.gmail.com
email.server.port=587
email.server.username=neasaa.finance@gmail.com
email.server.password=
email.server.smtp.auth=true
email.server.smtp.starttls.enable=true
